apiVersion: v1
entries:
  etcd-defrag-controller:
  - apiVersion: v2
    appVersion: v0.0.2
    created: "2024-08-13T16:47:45.466395+03:00"
    description: A Helm chart to install etcd defrag controller
    digest: dc9e51104acd617568ba247d45c34ff32b258964e5700a1277604795ea00e60d
    home: https://github.com/kaasops/etcd-defrag-controller
    name: etcd-defrag-controller
    sources:
    - https://github.com/kaasops/etcd-defrag-controller
    type: application
    urls:
    - https://kaasops.github.io/etcd-defrag-controller/helm/packages/etcd-defrag-controller-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2024-08-13T16:47:45.466293+03:00"
    description: A Helm chart to install etcd defrag controller
    digest: 4a0c32850669adb1ac2d7ad3940da2e0faf4eb3ad773887f97e2180fc2baffe4
    home: https://github.com/kaasops/etcd-defrag-controller
    name: etcd-defrag-controller
    sources:
    - https://github.com/kaasops/etcd-defrag-controller
    type: application
    urls:
    - https://kaasops.github.io/etcd-defrag-controller/helm/packages/etcd-defrag-controller-0.0.1.tgz
    version: 0.0.1
generated: "2024-08-13T16:47:45.465908+03:00"
